name: Run Flask App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize database
      run: python -c "import sqlite3; sqlite3.connect('users.db').close()"  # Initialize the database

    - name: Run the Flask app
      run: |
        python app.py &  # Run Flask app in the background
        sleep 5  # Give the server time to start
        # Here we should ideally call API endpoints to test
        curl -X POST http://127.0.0.1:5000/register -H "Content-Type: application/json" -d '{"email": "test@example.com", "password": "yourpassword"}'
        curl -X POST http://127.0.0.1:5000/login -H "Content-Type: application/json" -d '{"email": "test@example.com", "password": "yourpassword"}'
