name: Run Python HTTP Server

on:
  push:
    branches:
      - main  # Change to your default branch if different
  workflow_dispatch:

jobs:
  run_server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Change to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # No need to install sqlite3 as it's built-in with Python
          
      - name: Run HTTP Server
        run: |
          python app.py
        # Add `background: true` if needed, but be aware it might not be accessible outside
